import { PrismaClient } from '@prisma/client';
import { hashPassword } from '../src/lib/password.js';
import {
  resetBookingFixtures,
  resetCustomerPublicFixtures,
  resetTourWorkflowFixtures,
  resetVoucherFixtures,
} from '../src/lib/booking-fixtures.js';

const prisma = new PrismaClient();

const CUSTOMER_AVATAR =
  'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2296%22 height=%2296%22 viewBox=%220 0 96 96%22%3E%3Crect width=%2296%22 height=%2296%22 rx=%2248%22 fill=%22%23f5efe6%22/%3E%3Ccircle cx=%2248%22 cy=%2236%22 r=%2217%22 fill=%22%232d5a45%22/%3E%3Cpath d=%22M18 88c5-19 17-29 30-29s25 10 30 29%22 fill=%22%232d5a45%22/%3E%3Ctext x=%2248%22 y=%2290%22 text-anchor=%22middle%22 font-size=%2211%22 font-family=%22Arial, sans-serif%22 font-weight=%22700%22 fill=%22%23c59d3f%22%3EKH%3C/text%3E%3C/svg%3E';

function toDate(value: string) {
  return new Date(value);
}

async function main() {
  await prisma.paymentTransaction.deleteMany();
  await prisma.emailOutbox.deleteMany();
  await prisma.tourReview.deleteMany();
  await prisma.wishlistItem.deleteMany();
  await prisma.bookingPassenger.deleteMany();
  await prisma.booking.deleteMany();
  await prisma.tourInstance.deleteMany();
  await prisma.voucherTarget.deleteMany();
  await prisma.voucher.deleteMany();
  await prisma.specialDay.deleteMany();
  await prisma.province.deleteMany();
  await prisma.tourProgram.deleteMany();
  await prisma.supplierServicePrice.deleteMany();
  await prisma.supplierServiceVariant.deleteMany();
  await prisma.supplier.deleteMany();
  await prisma.servicePrice.deleteMany();
  await prisma.service.deleteMany();
  await prisma.tourGuide.deleteMany();
  await prisma.blogPost.deleteMany();
  await prisma.refreshToken.deleteMany();
  await prisma.user.deleteMany();

  const defaultPasswordHash = await hashPassword('123456');

  const [admin, manager, coordinator, sales, customer] = await Promise.all([
    prisma.user.create({
      data: {
        email: 'admin@travela.vn',
        fullName: 'Quản trị viên',
        phone: '0901234567',
        role: 'ADMIN',
        status: 'ACTIVE',
        passwordHash: defaultPasswordHash,
      },
    }),
    prisma.user.create({
      data: {
        email: 'manager@travela.vn',
        fullName: 'Quản lý kinh doanh',
        phone: '0901234568',
        role: 'MANAGER',
        status: 'ACTIVE',
        passwordHash: defaultPasswordHash,
      },
    }),
    prisma.user.create({
      data: {
        email: 'coordinator@travela.vn',
        fullName: 'Điều phối viên',
        phone: '0901234569',
        role: 'COORDINATOR',
        status: 'ACTIVE',
        passwordHash: defaultPasswordHash,
      },
    }),
    prisma.user.create({
      data: {
        email: 'sales@travela.vn',
        fullName: 'Nhân viên kinh doanh',
        phone: '0901234570',
        role: 'SALES',
        status: 'ACTIVE',
        passwordHash: defaultPasswordHash,
      },
    }),
    prisma.user.create({
      data: {
        email: 'customer@travela.vn',
        fullName: 'Khách hàng',
        phone: '0988888888',
        role: 'CUSTOMER',
        status: 'ACTIVE',
        avatarUrl: CUSTOMER_AVATAR,
        passwordHash: defaultPasswordHash,
      },
    }),
  ]);

  await prisma.province.createMany({
    data: [
      { code: 'HN', name: 'Hà Nội', hasAirport: true },
      { code: 'HCM', name: 'Hồ Chí Minh', hasAirport: true },
      { code: 'DN', name: 'Đà Nẵng', hasAirport: true },
      { code: 'QN', name: 'Quảng Ninh', hasAirport: true },
      { code: 'NB', name: 'Ninh Bình', hasAirport: false },
      { code: 'LC', name: 'Lào Cai', hasAirport: true },
      { code: 'NT', name: 'Ninh Thuận', hasAirport: false },
      { code: 'KH', name: 'Khánh Hòa', hasAirport: true },
      { code: 'QT', name: 'Quảng Trị', hasAirport: false },
      { code: 'QB', name: 'Quảng Bình', hasAirport: true },
      { code: 'HP', name: 'Hải Phòng', hasAirport: true },
      { code: 'CT', name: 'Cần Thơ', hasAirport: true },
    ],
  });

  await prisma.specialDay.createMany({
    data: [
      { code: 'SD001', name: 'Tết Nguyên Đán 2026', occasion: 'Lễ Tết', startDate: toDate('2026-02-17'), endDate: toDate('2026-02-23'), note: 'Kỳ nghỉ Tết âm lịch' },
      { code: 'SD002', name: 'Giỗ Tổ Hùng Vương', occasion: 'Lễ quốc gia', startDate: toDate('2026-04-06'), endDate: toDate('2026-04-06'), note: 'Giỗ Tổ Hùng Vương' },
      { code: 'SD003', name: 'Giải phóng Miền Nam', occasion: 'Lễ quốc gia', startDate: toDate('2026-04-30'), endDate: toDate('2026-04-30'), note: '30/4' },
      { code: 'SD004', name: 'Quốc tế Lao động', occasion: 'Lễ quốc gia', startDate: toDate('2026-05-01'), endDate: toDate('2026-05-01'), note: '1/5' },
      { code: 'SD005', name: 'Quốc khánh', occasion: 'Lễ quốc gia', startDate: toDate('2026-09-02'), endDate: toDate('2026-09-02'), note: '2/9' },
      { code: 'SD006', name: 'Mùa thu Nhật Bản', occasion: 'Mùa lễ quốc tế', startDate: toDate('2026-10-15'), endDate: toDate('2026-10-28'), note: 'Mùa lá đỏ' },
      { code: 'SD007', name: 'Giáng Sinh', occasion: 'Lễ quốc tế', startDate: toDate('2026-12-25'), endDate: toDate('2026-12-25'), note: 'Noel' },
    ],
  });

  const publicTours = [
    {
      id: 'T001',
      slug: 'kham-pha-vinh-ha-long-du-thuyen-5-sao',
      title: 'Khám Phá Vịnh Hạ Long - Du Thuyền 5 Sao',
      description: 'Trải nghiệm hoàng hôn rực rỡ trên vịnh di sản cùng dịch vụ nhà hàng fine-dining trên du thuyền Ambassador.',
      highlights: ['Nghỉ đêm trên du thuyền', 'Sunset party', 'Chèo kayak hang Luồn'],
      duration: { days: 3, nights: 2 },
      price: { adult: 4500000, child: 2250000, infant: 0 },
      originalPrice: 5500000,
      image: 'https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=1400',
      gallery: [
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1400',
        'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=1400',
      ],
      startDate: '2026-04-10',
      availableSeats: 12,
      minParticipants: 8,
      status: 'published',
      category: 'domestic',
      itinerary: [
        { day: 1, title: 'Hà Nội - Vịnh Hạ Long', description: 'Đón khách tại Hà Nội, check-in du thuyền.', activities: ['Nhận phòng', 'Tiệc tối'], meals: ['lunch', 'dinner'] },
        { day: 2, title: 'Khám phá vịnh', description: 'Thăm hang Sửng Sốt và bãi Ti Tốp.', activities: ['Hang Sửng Sốt', 'Ti Tốp'], meals: ['breakfast', 'lunch', 'dinner'] },
        { day: 3, title: 'Trở về Hà Nội', description: 'Ngắm bình minh và brunch trên tàu.', activities: ['Thái cực quyền', 'Brunch'], meals: ['breakfast', 'lunch'] },
      ],
      departurePoint: 'Hà Nội',
      sightseeingSpots: ['Quảng Ninh'],
      transport: 'xe',
      tourType: 'quanh_nam',
      bookingDeadline: 7,
      weekdays: ['t4', 't6', 'cn'],
      yearRoundStartDate: '2026-04-01',
      yearRoundEndDate: '2026-09-30',
      coverageMonths: 3,
      departureSchedule: [
        { id: 'DS001-1', date: '2026-04-10', availableSeats: 12, status: 'open', priceAdult: 4500000, priceChild: 2250000, priceInfant: 0 },
        { id: 'DS001-2', date: '2026-04-17', availableSeats: 8, status: 'filling', priceAdult: 4500000, priceChild: 2250000, priceInfant: 0 },
        { id: 'DS001-3', date: '2026-04-24', availableSeats: 12, status: 'open', priceAdult: 4500000, priceChild: 2250000, priceInfant: 0 },
        { id: 'DS001-4', date: '2026-05-01', availableSeats: 12, status: 'open', priceAdult: 4800000, priceChild: 2400000, priceInfant: 0, singleRoomSurcharge: 500000 },
        { id: 'DS001-5', date: '2026-05-08', availableSeats: 0, status: 'full', priceAdult: 4500000, priceChild: 2250000, priceInfant: 0 },
      ],
      inclusions: ['Xe Limousine đưa đón khứ hồi', '02 đêm nghỉ trên du thuyền', 'Bữa ăn theo chương trình (3 bữa/ngày)', 'Vé tham quan hang động', 'Chèo Kayak', 'Bảo hiểm du lịch'],
      exclusions: ['Chi phí cá nhân, đồ uống ngoài thực đơn', 'Tiền tip cho hướng dẫn viên và lái xe', 'VAT nếu yêu cầu xuất hóa đơn'],
      childPolicy: 'Trẻ em (dưới 12 tuổi): 50% giá người lớn. Trẻ sơ sinh (dưới 2 tuổi): miễn phí (không chiếm ghế).',
      cancellationPolicy: [
        { daysBefore: 30, refundPercent: 100 },
        { daysBefore: 15, refundPercent: 70 },
        { daysBefore: 7, refundPercent: 50 },
      ],
      rating: 4.9,
      reviewCount: 128,
    },
    {
      id: 'T002',
      slug: 'amanoi-ninh-thuan-resort-chi-mang-tinh-chat-nghi-duong',
      title: 'Amanoi Ninh Thu?n - Tr?i Nghi?m T?nh T?i',
      description: 'Ngh? d??ng cao c?p t?i Amanoi v?i kh?ng gian ri?ng t? v? d?ch v? ch?m s?c s?c kh?e.',
      highlights: ['Bi?t th? h? b?i', 'Spa', 'B?a t?i ri?ng t?'],
      duration: { days: 4, nights: 3 },
      price: { adult: 28000000, child: 14000000, infant: 2800000 },
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1400',
      gallery: [
        'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=1400',
        'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=1400',
      ],
      startDate: '2026-05-01',
      availableSeats: 4,
      minParticipants: 2,
      status: 'published',
      category: 'domestic',
      itinerary: [
        { day: 1, title: 'S?n bay Cam Ranh - Amanoi', description: 'Check-in bi?t th? ngh? d??ng.', activities: ['Check-in'], meals: ['lunch', 'dinner'] },
        { day: 2, title: 'H?nh tr?nh n??c', description: 'Du thuy?n ri?ng v? snorkeling.', activities: ['Du thuy?n', 'Snorkeling'], meals: ['breakfast', 'lunch', 'dinner'] },
        { day: 3, title: 'Tĩnh tại', description: 'Yoga và trekking nhẹ.', activities: ['Yoga', 'Trekking'], meals: ['breakfast', 'lunch', 'dinner'] },
        { day: 4, title: 'T?m bi?t', description: 'Tr? ph?ng v? ra s?n bay.', activities: ['Tr? ph?ng'], meals: ['breakfast'] },
      ],
      departurePoint: 'H? Ch? Minh',
      sightseeingSpots: ['Ninh Thu?n'],
      transport: 'xe',
      tourType: 'quanh_nam',
      bookingDeadline: 14,
      weekdays: ['t5', 'cn'],
      yearRoundStartDate: '2026-05-01',
      yearRoundEndDate: '2026-12-31',
      coverageMonths: 6,
      departureSchedule: [
        { id: 'DS002-1', date: '2026-05-01', availableSeats: 4, status: 'open', priceAdult: 28000000, priceChild: 14000000, priceInfant: 2800000 },
        { id: 'DS002-2', date: '2026-05-15', availableSeats: 4, status: 'open', priceAdult: 28000000, priceChild: 14000000, priceInfant: 2800000 },
      ],
      inclusions: ['Xe đưa đón', '03 đêm Amanoi', 'Spa 60 phút/ngày'],
      exclusions: ['Vé máy bay', 'Chi phí cá nhân'],
      childPolicy: 'Trẻ em dưới 12 tuổi tính 50% giá người lớn.',
      cancellationPolicy: [
        { daysBefore: 14, refundPercent: 100 },
        { daysBefore: 7, refundPercent: 50 },
      ],
      rating: 4.8,
      reviewCount: 56,
    },
    {
      id: 'T003',
      slug: 'kham-pha-mua-thu-kyoto-chuyen-bay-thang',
      title: 'Mùa Thu Kyoto & Osaka - Vẻ Đẹp Vĩnh Cửu',
      description: 'Hành trình 6 ngày khám phá Kyoto và Osaka trong mùa lá đỏ.',
      highlights: ['Kimono', 'Kaiseki', 'Onsen'],
      duration: { days: 6, nights: 5 },
      price: { adult: 32000000, child: 26000000, infant: 8000000 },
      originalPrice: 35000000,
      image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1400',
      gallery: [
        'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?q=80&w=1400',
        'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?q=80&w=1400',
      ],
      startDate: '2026-10-15',
      availableSeats: 25,
      minParticipants: 10,
      status: 'published',
      category: 'international',
      itinerary: [
        { day: 1, title: 'H? N?i - Osaka', description: 'Bay th?ng ??n Osaka.', activities: ['Nh?n ph?ng'], meals: ['lunch'] },
        { day: 2, title: 'Khám phá Osaka', description: 'Tham quan lâu đài Osaka.', activities: ['Lâu đài Osaka', 'Dotonbori'], meals: ['breakfast', 'dinner'] },
        { day: 3, title: 'C? ?? Kyoto', description: 'Th?m Kinkakuji v? tr?i nghi?m tr? ??o.', activities: ['Kinkakuji', 'Tr? ??o'], meals: ['breakfast', 'lunch', 'dinner'] },
        { day: 4, title: 'Arashiyama', description: 'R?ng tr?c v? b?a t?i Kaiseki.', activities: ['R?ng tr?c', 'Kaiseki'], meals: ['breakfast', 'lunch', 'dinner'] },
        { day: 5, title: 'Nara', description: 'Công viên hươu và mua sắm.', activities: ['Nara', 'Mua sắm'], meals: ['breakfast', 'lunch'] },
        { day: 6, title: 'Osaka - H? N?i', description: 'Onsen s?ng v? k?t th?c h?nh tr?nh.', activities: ['Onsen'], meals: ['breakfast'] },
      ],
      departurePoint: 'H? N?i',
      sightseeingSpots: ['Osaka', 'Kyoto', 'Nara'],
      transport: 'maybay',
      arrivalPoint: 'Osaka',
      tourType: 'mua_le',
      holiday: 'Mùa thu Nhật Bản',
      bookingDeadline: 21,
      selectedDates: ['2026-10-15', '2026-10-20'],
      departureSchedule: [
        { id: 'DS003-1', date: '2026-10-15', availableSeats: 25, status: 'open', priceAdult: 32000000, priceChild: 26000000, priceInfant: 8000000 },
        { id: 'DS003-2', date: '2026-10-20', availableSeats: 18, status: 'open', priceAdult: 32000000, priceChild: 26000000, priceInfant: 8000000 },
      ],
      inclusions: ['V? m?y bay', 'Kh?ch s?n 4 sao', '?n theo ch??ng tr?nh', 'B?o hi?m'],
      exclusions: ['Chi phí cá nhân', 'VAT'],
      childPolicy: 'Trẻ em 2-11 tuổi tính 81% giá người lớn.',
      cancellationPolicy: [
        { daysBefore: 30, refundPercent: 100 },
        { daysBefore: 21, refundPercent: 80 },
        { daysBefore: 14, refundPercent: 50 },
      ],
      rating: 4.7,
      reviewCount: 89,
    },
  ];

  Object.assign(publicTours[0], {
    title: 'Khám Phá Vịnh Hạ Long - Du Thuyền 5 Sao',
    description: 'Trải nghiệm vịnh di sản trên du thuyền cao cấp, ngắm hoàng hôn, chèo kayak và thưởng thức ẩm thực trên vịnh.',
    highlights: ['Nghỉ đêm trên du thuyền', 'Sunset party', 'Chèo kayak hang Luồn'],
    departurePoint: 'Hà Nội',
    sightseeingSpots: ['Quảng Ninh', 'Vịnh Hạ Long', 'Hang Sửng Sốt'],
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=1400',
    gallery: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1400',
      'https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=1400',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=1400',
    ],
    inclusions: ['Xe Limousine đưa đón khứ hồi', '02 đêm nghỉ trên du thuyền', 'Bữa ăn theo chương trình', 'Vé tham quan hang động', 'Chèo kayak', 'Bảo hiểm du lịch'],
    exclusions: ['Chi phí cá nhân, đồ uống ngoài thực đơn', 'Tiền tip cho hướng dẫn viên và lái xe', 'VAT nếu yêu cầu xuất hóa đơn'],
    childPolicy: 'Trẻ em dưới 12 tuổi tính 50% giá người lớn. Trẻ sơ sinh dưới 2 tuổi miễn phí.',
    itinerary: [
      { day: 1, title: 'Hà Nội - Vịnh Hạ Long', description: 'Đón khách tại Hà Nội, check-in du thuyền và dùng bữa tối trên vịnh.', activities: ['Nhận phòng', 'Tiệc tối'], meals: ['lunch', 'dinner'] },
      { day: 2, title: 'Khám phá vịnh', description: 'Thăm hang Sửng Sốt, bãi Ti Tốp và chèo kayak.', activities: ['Hang Sửng Sốt', 'Ti Tốp', 'Kayak'], meals: ['breakfast', 'lunch', 'dinner'] },
      { day: 3, title: 'Trở về Hà Nội', description: 'Ngắm bình minh, dùng brunch trên tàu và trở về Hà Nội.', activities: ['Thái cực quyền', 'Brunch'], meals: ['breakfast', 'lunch'] },
    ],
  });

  Object.assign(publicTours[1], {
    title: 'Amanoi Ninh Thuận - Trải Nghiệm Tĩnh Tại',
    description: 'Nghỉ dưỡng cao cấp tại vịnh Vĩnh Hy với biệt thự riêng tư, spa, yoga và lịch trình chăm sóc sức khỏe.',
    highlights: ['Biệt thự hồ bơi', 'Spa chăm sóc sức khỏe', 'Bữa tối riêng tư'],
    departurePoint: 'Hồ Chí Minh',
    sightseeingSpots: ['Ninh Thuận', 'Vĩnh Hy', 'Núi Chúa'],
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1400',
    gallery: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1400',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=1400',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=1400',
    ],
    childPolicy: 'Trẻ em dưới 12 tuổi tính 50% giá người lớn.',
    itinerary: [
      { day: 1, title: 'Sân bay Cam Ranh - Amanoi', description: 'Đón khách tại sân bay, di chuyển về resort và check-in biệt thự.', activities: ['Đón sân bay', 'Check-in'], meals: ['lunch', 'dinner'] },
      { day: 2, title: 'Vịnh Vĩnh Hy', description: 'Du thuyền riêng, snorkeling và ăn trưa ven biển.', activities: ['Du thuyền', 'Snorkeling'], meals: ['breakfast', 'lunch', 'dinner'] },
      { day: 3, title: 'Tĩnh tại', description: 'Yoga, spa và trekking nhẹ trong khu bảo tồn Núi Chúa.', activities: ['Yoga', 'Spa', 'Trekking'], meals: ['breakfast', 'lunch', 'dinner'] },
      { day: 4, title: 'Tạm biệt Ninh Thuận', description: 'Trả phòng và ra sân bay.', activities: ['Trả phòng'], meals: ['breakfast'] },
    ],
  });

  Object.assign(publicTours[2], {
    title: 'Mùa Thu Kyoto & Osaka - Vẻ Đẹp Vĩnh Cửu',
    description: 'Hành trình 6 ngày khám phá Kyoto, Osaka và Nara trong mùa lá đỏ Nhật Bản.',
    highlights: ['Trải nghiệm kimono', 'Ẩm thực kaiseki', 'Onsen'],
    departurePoint: 'Hà Nội',
    sightseeingSpots: ['Osaka', 'Kyoto', 'Nara'],
    lodgingStandard: '4 sao',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1400',
    gallery: [
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1400',
      'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?q=80&w=1400',
      'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?q=80&w=1400',
    ],
    holiday: 'Mùa thu Nhật Bản',
    inclusions: ['Vé máy bay', 'Khách sạn 4 sao', 'Ăn theo chương trình', 'Bảo hiểm du lịch'],
    exclusions: ['Chi phí cá nhân', 'VAT nếu yêu cầu xuất hóa đơn'],
    childPolicy: 'Trẻ em 2-11 tuổi tính 81% giá người lớn.',
    itinerary: [
      { day: 1, title: 'Hà Nội - Osaka', description: 'Bay thẳng đến Osaka, nhận phòng và nghỉ ngơi.', activities: ['Bay quốc tế', 'Check-in'], meals: ['dinner'] },
      { day: 2, title: 'Osaka', description: 'Tham quan thành Osaka, Dotonbori và trải nghiệm ẩm thực đường phố.', activities: ['Thành Osaka', 'Dotonbori'], meals: ['breakfast', 'lunch', 'dinner'] },
      { day: 3, title: 'Kyoto', description: 'Khám phá Fushimi Inari, Gion và phố cổ Kyoto.', activities: ['Fushimi Inari', 'Gion'], meals: ['breakfast', 'lunch', 'dinner'] },
      { day: 4, title: 'Nara', description: 'Thăm công viên Nara và chùa Todai-ji.', activities: ['Nara Park', 'Todai-ji'], meals: ['breakfast', 'lunch'] },
      { day: 5, title: 'Onsen', description: 'Nghỉ dưỡng onsen và dùng bữa kaiseki.', activities: ['Onsen', 'Kaiseki'], meals: ['breakfast', 'dinner'] },
      { day: 6, title: 'Osaka - Hà Nội', description: 'Tự do mua sắm trước giờ ra sân bay.', activities: ['Mua sắm', 'Bay về'], meals: ['breakfast'] },
    ],
  });
  const [tp1, tp2, tp3, tp4] = await Promise.all([
    prisma.tourProgram.create({
      data: {
        code: 'TP001',
        name: publicTours[0].title,
        slug: publicTours[0].slug,
        description: publicTours[0].description,
        departurePoint: publicTours[0].departurePoint,
        arrivalPoint: null,
        sightseeingSpots: publicTours[0].sightseeingSpots,
        durationDays: publicTours[0].duration.days,
        durationNights: publicTours[0].duration.nights,
        transport: 'XE',
        tourType: 'QUANH_NAM',
        bookingDeadline: 7,
        status: 'ACTIVE',
        itineraryJson: publicTours[0].itinerary.map((day) => ({
          day: day.day,
          title: day.title,
          description: day.description,
          meals: day.meals,
          accommodationPoint: day.day <= publicTours[0].duration.nights ? 'Qu\u1ea3ng Ninh' : undefined,
        })),
        pricingConfigJson: {
          pricingConfig: {
            profitMargin: 20,
            taxRate: 10,
            otherCostFactor: 0.05,
            netPrice: 0,
            sellPriceAdult: 4500000,
            sellPriceChild: 2250000,
            sellPriceInfant: 0,
            minParticipants: 8,
            guideUnitPrice: 1500000,
          },
          draftPricingTables: {
            transport: [{ optionId: 'SUP002-SUP002-S1', isDefault: true, manualPrice: 8100000 }],
            flight: [],
            hotels: {
              'stay-1': [{ optionId: 'SUP001', isDefault: true }],
            },
            meals: {
              'meal-1-lunch': [{ optionId: 'SUP005-S1', isDefault: true }],
              'meal-2-breakfast': [{ optionId: 'SUP001-M1', isDefault: true }],
            },
            attractions: {
              'attraction-1': [{ optionId: 'SV-TKT', isDefault: true }],
            },
            otherCosts: [{ optionId: 'SV-INS', isDefault: true }],
          },
          draftManualPricing: {},
          draftPricingOverrides: {},
        },
        publicContentJson: {
          ...publicTours[0],
          lodgingStandard: '4 sao',
          priceIncludes: publicTours[0].inclusions.join('\n'),
          priceExcludes: publicTours[0].exclusions.join('\n'),
        },
        createdById: coordinator.id,
        updatedById: coordinator.id,
      },
    }),
    prisma.tourProgram.create({
      data: {
        code: 'TP002',
        name: publicTours[1].title,
        slug: publicTours[1].slug,
        description: publicTours[1].description,
        departurePoint: publicTours[1].departurePoint,
        arrivalPoint: null,
        sightseeingSpots: publicTours[1].sightseeingSpots,
        durationDays: publicTours[1].duration.days,
        durationNights: publicTours[1].duration.nights,
        transport: 'XE',
        tourType: 'QUANH_NAM',
        bookingDeadline: 14,
        status: 'ACTIVE',
        itineraryJson: publicTours[1].itinerary.map((day) => ({
          day: day.day,
          title: day.title,
          description: day.description,
          meals: day.meals,
        })),
        pricingConfigJson: {
          profitMargin: 18,
          taxRate: 10,
          otherCostFactor: 0.08,
          netPrice: 0,
          sellPriceAdult: 28000000,
          sellPriceChild: 14000000,
          sellPriceInfant: 2800000,
          minParticipants: 2,
        },
        publicContentJson: publicTours[1],
        createdById: coordinator.id,
        updatedById: coordinator.id,
      },
    }),
    prisma.tourProgram.create({
      data: {
        code: 'TP003',
        name: publicTours[2].title,
        slug: publicTours[2].slug,
        description: publicTours[2].description,
        departurePoint: publicTours[2].departurePoint,
        arrivalPoint: 'Osaka',
        sightseeingSpots: publicTours[2].sightseeingSpots,
        durationDays: publicTours[2].duration.days,
        durationNights: publicTours[2].duration.nights,
        transport: 'MAYBAY',
        tourType: 'MUA_LE',
        holidayLabel: 'Mùa thu Nhật Bản',
        bookingDeadline: 21,
        status: 'DRAFT',
        itineraryJson: publicTours[2].itinerary.map((day) => ({
          day: day.day,
          title: day.title,
          description: day.description,
          meals: day.meals,
        })),
        pricingConfigJson: {
          profitMargin: 18,
          taxRate: 10,
          otherCostFactor: 0.08,
          netPrice: 0,
          sellPriceAdult: 32000000,
          sellPriceChild: 26000000,
          sellPriceInfant: 8000000,
          minParticipants: 10,
        },
        publicContentJson: {
          ...publicTours[2],
          approvalStatus: 'rejected',
          rejectionReason: 'Thiếu dữ liệu đối tác khách sạn và cần cập nhật lại cấu hình giá.',
        },
        createdById: coordinator.id,
        updatedById: coordinator.id,
      },
    }),
    prisma.tourProgram.create({
      data: {
        code: 'TP004',
        name: 'Sapa - Ruộng Bậc Thang Mùa Hè 2N1Đ',
        slug: 'sapa-ruong-bac-thang-mua-ha-2n1d',
        description: 'Chương trình Sapa đang ngừng hoạt động để rà soát lại đối tác và chính sách giá.',
        departurePoint: 'Hà Nội',
        sightseeingSpots: ['Sapa', 'Bản Cát Cát', 'Núi Hàm Rồng'],
        durationDays: 2,
        durationNights: 1,
        transport: 'XE',
        tourType: 'QUANH_NAM',
        bookingDeadline: 10,
        status: 'INACTIVE',
        itineraryJson: [
          { day: 1, title: 'Hà Nội - Sapa', description: 'Di chuyển lên Sapa.', meals: ['lunch', 'dinner'] },
          { day: 2, title: 'Sapa - Hà Nội', description: 'Trở về Hà Nội.', meals: ['breakfast', 'lunch'] },
        ],
        pricingConfigJson: {
          profitMargin: 18,
          taxRate: 10,
          otherCostFactor: 0.05,
          netPrice: 0,
          sellPriceAdult: 2200000,
          sellPriceChild: 1600000,
          sellPriceInfant: 0,
          minParticipants: 10,
        },
        publicContentJson: {
          lodgingStandard: '4 sao',
          yearRoundStartDate: '2026-06-01',
          yearRoundEndDate: '2026-09-30',
          weekdays: ['t6'],
          coverageMonths: 3,
          inactiveReason: 'T\u1ea1m d\u1eebng \u0111\u1ec3 c\u1eadp nh\u1eadt l\u1ea1i gi\u00e1 ph\u00f2ng v\u00e0 \u0111\u1ed1i t\u00e1c v\u1eadn chuy\u1ec3n',
          approvalStatus: 'approved',
        },
        createdById: coordinator.id,
        updatedById: coordinator.id,
      },
    }),
  ]);

  const buildHaLongCostEstimate = (guestCount: number) => {
    const doubleRooms = Math.max(1, Math.ceil(guestCount / 2));
    const categories = [
      {
        id: 'A',
        name: 'Vận chuyển',
        isFixed: true,
        items: [{
          id: 1,
          name: 'Xe vận chuyển',
          unit: 'chuyến',
          target: 'all',
          quantity: 1,
          nightsOrRuns: 1,
          unitPrice: 8100000,
          total: 8100000,
          primarySupplierId: 'A-transport-0',
          suppliers: [{ supplierId: 'A-transport-0', supplierName: 'Vận tải Xuyên Việt', serviceVariant: 'Xe 16 chỗ', quotedPrice: 8100000, notes: '', isPrimary: true }],
        }],
        subtotal: 8100000,
      },
      {
        id: 'B',
        name: 'Khách sạn',
        isFixed: false,
        items: [{
          id: 1,
          name: 'Lưu trú - Đêm 1, 2 - Phòng đôi',
          unit: 'phòng',
          target: 'adult',
          quantity: doubleRooms,
          nightsOrRuns: 2,
          unitPrice: 1300000,
          total: doubleRooms * 2 * 1300000,
          primarySupplierId: 'B-stay-1-double',
          suppliers: [{ supplierId: 'B-stay-1-double', supplierName: 'Khách sạn Di Sản Việt', serviceVariant: 'Phòng đôi', quotedPrice: 1300000, notes: '', isPrimary: true }],
        }],
        subtotal: doubleRooms * 2 * 1300000,
      },
      {
        id: 'C',
        name: 'Chi phí ăn',
        isFixed: false,
        items: [
          {
            id: 1,
            name: 'Ngày 1 - Bữa trưa',
            unit: 'khách',
            target: 'all',
            quantity: guestCount,
            nightsOrRuns: 1,
            unitPrice: 198000,
            total: guestCount * 198000,
            primarySupplierId: 'C-meal-1-lunch',
            suppliers: [{ supplierId: 'C-meal-1-lunch', supplierName: 'Hạ Long Harbor Dining', serviceVariant: 'Set hải sản đoàn', quotedPrice: 198000, notes: '', isPrimary: true }],
          },
          {
            id: 2,
            name: 'Ngày 2 - Bữa sáng',
            unit: 'khách',
            target: 'all',
            quantity: guestCount,
            nightsOrRuns: 1,
            unitPrice: 180000,
            total: guestCount * 180000,
            primarySupplierId: 'C-meal-2-breakfast',
            suppliers: [{ supplierId: 'C-meal-2-breakfast', supplierName: 'Khách sạn Di Sản Việt', serviceVariant: 'Buffet sáng', quotedPrice: 180000, notes: '', isPrimary: true }],
          },
        ],
        subtotal: guestCount * (198000 + 180000),
      },
      {
        id: 'D',
        name: 'Vé thắng cảnh',
        isFixed: false,
        items: [{
          id: 1,
          name: 'Ngày 1 - Người lớn',
          unit: 'khách',
          target: 'adult',
          quantity: guestCount,
          nightsOrRuns: 1,
          unitPrice: 250000,
          total: guestCount * 250000,
          primarySupplierId: 'D-attraction-1-adult',
          suppliers: [{ supplierId: 'D-attraction-1-adult', supplierName: 'Sun World Hạ Long', serviceVariant: 'Vé tham quan Sun World', quotedPrice: 250000, notes: '', isPrimary: true }],
        }],
        subtotal: guestCount * 250000,
      },
      {
        id: 'E',
        name: 'Hướng dẫn viên',
        isFixed: true,
        items: [{
          id: 1,
          name: 'Hướng dẫn viên',
          unit: 'đ',
          target: 'all',
          quantity: 1,
          nightsOrRuns: 1,
          unitPrice: 1500000,
          total: 1500000,
          primarySupplierId: 'E-guide',
          suppliers: [{ supplierId: 'E-guide', supplierName: 'Chưa phân công', serviceVariant: 'Hướng dẫn viên', quotedPrice: 1500000, notes: '', isPrimary: true }],
        }],
        subtotal: 1500000,
      },
      {
        id: 'F',
        name: 'Chi phí khác',
        isFixed: false,
        items: [{
          id: 1,
          name: 'Bảo hiểm du lịch',
          unit: 'lần',
          target: 'all',
          quantity: guestCount,
          nightsOrRuns: 1,
          unitPrice: 40000,
          total: guestCount * 40000,
          primarySupplierId: 'F-other-0',
          suppliers: [{ supplierId: 'F-other-0', supplierName: 'Bảo Việt Travel Care', serviceVariant: 'Bảo hiểm du lịch', quotedPrice: 40000, notes: '', isPrimary: true }],
        }],
        subtotal: guestCount * 40000,
      },
    ];
    const totalFixedCost = categories.filter((category) => category.isFixed).reduce((sum, category) => sum + category.subtotal, 0);
    const totalVariableCost = categories.filter((category) => !category.isFixed).reduce((sum, category) => sum + category.subtotal, 0);
    return {
      categories,
      totalFixedCost,
      totalVariableCost,
      totalCost: totalFixedCost + totalVariableCost,
      estimatedGuests: guestCount,
      pricingConfig: {
        profitMargin: 20,
        taxRate: 10,
        otherCostFactor: 0.05,
        netPrice: 0,
        sellPriceAdult: 4500000,
        sellPriceChild: 2250000,
        sellPriceInfant: 0,
        minParticipants: 8,
      },
    };
  };

  const buildKyotoCostEstimate = (guestCount: number) => {
    const categories = [
      {
        id: 'A',
        name: 'Vận chuyển',
        isFixed: false,
        items: [{
          id: 1,
          name: 'Vé máy bay đoàn',
          unit: 'vé',
          target: 'all',
          quantity: guestCount,
          nightsOrRuns: 1,
          unitPrice: 1850000,
          total: guestCount * 1850000,
          primarySupplierId: 'A-flight-0',
          suppliers: [{ supplierId: 'A-flight-0', supplierName: 'SkyLink Airways Services', serviceVariant: 'Vé máy bay đoàn nội địa', quotedPrice: 1850000, notes: '', isPrimary: true }],
        }],
        subtotal: guestCount * 1850000,
      },
      {
        id: 'E',
        name: 'Hướng dẫn viên',
        isFixed: true,
        items: [{
          id: 1,
          name: 'Hướng dẫn viên',
          unit: 'đ',
          target: 'all',
          quantity: 1,
          nightsOrRuns: 1,
          unitPrice: 2500000,
          total: 2500000,
          primarySupplierId: 'E-guide',
          suppliers: [{ supplierId: 'E-guide', supplierName: 'Chưa phân công', serviceVariant: 'Hướng dẫn viên', quotedPrice: 2500000, notes: '', isPrimary: true }],
        }],
        subtotal: 2500000,
      },
    ];
    const totalFixedCost = 2500000;
    const totalVariableCost = guestCount * 1850000;
    return {
      categories,
      totalFixedCost,
      totalVariableCost,
      totalCost: totalFixedCost + totalVariableCost,
      estimatedGuests: guestCount,
      pricingConfig: {
        profitMargin: 18,
        taxRate: 10,
        otherCostFactor: 0.08,
        netPrice: 0,
        sellPriceAdult: 32000000,
        sellPriceChild: 26000000,
        sellPriceInfant: 8000000,
        minParticipants: 10,
      },
    };
  };

  const instances = await Promise.all([
    prisma.tourInstance.create({
      data: {
        code: 'TI001',
        programId: tp1.id,
        programNameSnapshot: tp1.name,
        departureDate: toDate('2026-04-10'),
        bookingDeadlineAt: toDate('2026-04-03'),
        status: 'DANG_TRIEN_KHAI',
        departurePoint: 'Hà Nội',
        sightseeingSpots: ['Quảng Ninh'],
        transport: 'XE',
        expectedGuests: 10,
        minParticipants: 8,
        priceAdult: 4500000,
        priceChild: 2250000,
        priceInfant: 0,
        assignedCoordinatorId: coordinator.id,
        createdById: coordinator.id,
        openedAt: toDate('2026-03-25T00:00:00Z'),
        startedAt: toDate('2026-04-10T00:00:00Z'),
        costEstimateJson: buildHaLongCostEstimate(10),
        estimatedAt: toDate('2026-04-08T09:00:00Z'),
      },
    }),
    prisma.tourInstance.create({
      data: {
        code: 'TI002',
        programId: tp3.id,
        programNameSnapshot: tp3.name,
        departureDate: toDate('2026-10-15'),
        bookingDeadlineAt: toDate('2026-09-24'),
        status: 'SAN_SANG_TRIEN_KHAI',
        departurePoint: 'Hà Nội',
        arrivalPoint: 'Osaka',
        sightseeingSpots: ['Osaka', 'Kyoto', 'Nara'],
        transport: 'MAYBAY',
        expectedGuests: 15,
        minParticipants: 10,
        priceAdult: 32000000,
        priceChild: 26000000,
        priceInfant: 8000000,
        createdById: coordinator.id,
        approvedById: manager.id,
        submittedAt: toDate('2026-03-16T10:00:00Z'),
        approvedAt: toDate('2026-03-17T10:00:00Z'),
        openedAt: toDate('2026-03-18T00:00:00Z'),
        warningDate: toDate('2026-10-10'),
      },
    }),
    prisma.tourInstance.create({
      data: {
        code: 'TI003',
        programId: tp3.id,
        programNameSnapshot: tp3.name,
        departureDate: toDate('2026-10-20'),
        bookingDeadlineAt: toDate('2026-09-29'),
        status: 'DANG_MO_BAN',
        departurePoint: 'Hà Nội',
        arrivalPoint: 'Osaka',
        sightseeingSpots: ['Osaka', 'Kyoto', 'Nara'],
        transport: 'MAYBAY',
        expectedGuests: 18,
        minParticipants: 10,
        priceAdult: 32000000,
        priceChild: 26000000,
        priceInfant: 8000000,
        createdById: coordinator.id,
        approvedById: manager.id,
        submittedAt: toDate('2026-03-26T10:00:00Z'),
        approvedAt: toDate('2026-03-27T10:00:00Z'),
        openedAt: toDate('2026-03-28T00:00:00Z'),
        warningDate: toDate('2026-10-15'),
        costEstimateJson: buildKyotoCostEstimate(18),
        estimatedAt: toDate('2026-03-28T09:00:00Z'),
      },
    }),
    prisma.tourInstance.create({
      data: {
        code: 'TI004',
        programId: tp1.id,
        programNameSnapshot: tp1.name,
        departureDate: toDate('2026-04-17'),
        bookingDeadlineAt: toDate('2026-04-10'),
        status: 'CHO_QUYET_TOAN',
        departurePoint: 'Hà Nội',
        sightseeingSpots: ['Quảng Ninh'],
        transport: 'XE',
        expectedGuests: 8,
        minParticipants: 8,
        priceAdult: 4500000,
        priceChild: 2250000,
        priceInfant: 0,
        assignedCoordinatorId: coordinator.id,
        createdById: coordinator.id,
        openedAt: toDate('2026-03-12T00:00:00Z'),
        closedAt: toDate('2026-04-14T00:00:00Z'),
        receivedAt: toDate('2026-04-14T10:00:00Z'),
        readyAt: toDate('2026-04-15T10:00:00Z'),
        startedAt: toDate('2026-04-17T06:00:00Z'),
        endedAt: toDate('2026-04-19T18:00:00Z'),
        costEstimateJson: buildHaLongCostEstimate(8),
        estimatedAt: toDate('2026-04-15T09:00:00Z'),
      },
    }),
    prisma.tourInstance.create({
      data: {
        code: 'TI005',
        programId: tp2.id,
        programNameSnapshot: tp2.name,
        departureDate: toDate('2026-05-01'),
        bookingDeadlineAt: toDate('2026-04-30T23:59:59+07:00'),
        status: 'DANG_MO_BAN',
        departurePoint: 'Hồ Chí Minh',
        sightseeingSpots: ['Ninh Thuận'],
        transport: 'XE',
        expectedGuests: 4,
        minParticipants: 2,
        priceAdult: 28000000,
        priceChild: 14000000,
        priceInfant: 2800000,
        createdById: coordinator.id,
        openedAt: toDate('2026-03-25T00:00:00Z'),
      },
    }),
    prisma.tourInstance.create({
      data: {
        code: 'TI006',
        programId: tp1.id,
        programNameSnapshot: tp1.name,
        departureDate: toDate('2026-03-20'),
        bookingDeadlineAt: toDate('2026-03-13'),
        status: 'DA_HUY',
        departurePoint: 'Hà Nội',
        sightseeingSpots: ['Quảng Ninh'],
        transport: 'XE',
        expectedGuests: 5,
        minParticipants: 8,
        priceAdult: 4500000,
        priceChild: 2250000,
        priceInfant: 0,
        createdById: coordinator.id,
        openedAt: toDate('2026-03-05T00:00:00Z'),
        closedAt: toDate('2026-03-17T00:00:00Z'),
        cancelledAt: toDate('2026-03-17T12:00:00Z'),
        cancelReason: 'Không đủ khách tối thiểu (chỉ có 5/8)',
        refundTotal: 11250000,
      },
    }),
    prisma.tourInstance.create({
      data: {
        code: 'TI007',
        programId: tp3.id,
        programNameSnapshot: tp3.name,
        departureDate: toDate('2026-10-20'),
        bookingDeadlineAt: toDate('2026-09-29'),
        status: 'DANG_MO_BAN',
        departurePoint: 'Hà Nội',
        arrivalPoint: 'Osaka',
        sightseeingSpots: ['Osaka', 'Kyoto', 'Nara'],
        transport: 'MAYBAY',
        expectedGuests: 18,
        minParticipants: 10,
        priceAdult: 32000000,
        priceChild: 26000000,
        priceInfant: 8000000,
        createdById: coordinator.id,
        approvedById: manager.id,
        submittedAt: toDate('2026-03-26T10:00:00Z'),
        approvedAt: toDate('2026-03-27T10:00:00Z'),
        openedAt: toDate('2026-03-28T00:00:00Z'),
        warningDate: toDate('2026-10-15'),
      },
    }),
    prisma.tourInstance.create({
      data: {
        code: 'TI008',
        programId: tp1.id,
        programNameSnapshot: tp1.name,
        departureDate: toDate('2026-04-24'),
        bookingDeadlineAt: toDate('2026-04-17'),
        status: 'CHO_NHAN_DIEU_HANH',
        departurePoint: 'Hà Nội',
        sightseeingSpots: ['Quảng Ninh'],
        transport: 'XE',
        expectedGuests: 12,
        minParticipants: 8,
        priceAdult: 4500000,
        priceChild: 2250000,
        priceInfant: 0,
        assignedCoordinatorId: coordinator.id,
        createdById: coordinator.id,
        openedAt: toDate('2026-03-18T00:00:00Z'),
        closedAt: toDate('2026-04-21T00:00:00Z'),
      },
    }),
    prisma.tourInstance.create({
      data: {
        code: 'TI009',
        programId: tp1.id,
        programNameSnapshot: tp1.name,
        departureDate: toDate('2026-05-22'),
        bookingDeadlineAt: toDate('2026-05-15'),
        status: 'CHO_DU_TOAN',
        departurePoint: 'Hà Nội',
        sightseeingSpots: ['Quảng Ninh'],
        transport: 'XE',
        expectedGuests: 10,
        minParticipants: 8,
        priceAdult: 4700000,
        priceChild: 2350000,
        priceInfant: 0,
        assignedCoordinatorId: coordinator.id,
        createdById: coordinator.id,
        openedAt: toDate('2026-03-22T00:00:00Z'),
        closedAt: toDate('2026-05-18T00:00:00Z'),
        receivedAt: toDate('2026-05-18T10:00:00Z'),
      },
    }),
    prisma.tourInstance.create({
      data: {
        code: 'TI010',
        programId: tp1.id,
        programNameSnapshot: tp1.name,
        departureDate: toDate('2026-05-01'),
        bookingDeadlineAt: toDate('2026-04-30T23:59:59+07:00'),
        status: 'DANG_MO_BAN',
        departurePoint: 'Hà Nội',
        sightseeingSpots: ['Quảng Ninh'],
        transport: 'XE',
        expectedGuests: 12,
        minParticipants: 8,
        priceAdult: 4800000,
        priceChild: 2400000,
        priceInfant: 0,
        createdById: coordinator.id,
        approvedById: manager.id,
        submittedAt: toDate('2026-03-27T10:00:00Z'),
        approvedAt: toDate('2026-03-28T10:00:00Z'),
        openedAt: toDate('2026-04-01T00:00:00Z'),
      },
    }),
  ]);

  await prisma.supplier.createMany({
    data: [
      {
        id: 'SUP001',
        name: 'Kh\u00e1ch s\u1ea1n Di S\u1ea3n Vi\u1ec7t',
        phone: '024 3939 8888',
        email: 'contact@heritage.vn',
        type: 'HOTEL',
        serviceSummary: 'L\u01b0u tr\u00fa',
        operatingArea: 'Qu\u1ea3ng Ninh, H\u1ea1 Long',
        address: '12 B\u00e3i Ch\u00e1y, H\u1ea1 Long, Qu\u1ea3ng Ninh',
        establishedYear: 2016,
        description: 'Kh\u00e1ch s\u1ea1n 4 sao ph\u1ee5c v\u1ee5 kh\u00e1ch \u0111o\u00e0n, c\u00f3 nh\u00e0 h\u00e0ng n\u1ed9i khu.',
        standardsJson: ['4 sao'],
        isActive: true,
      },
      {
        id: 'SUP002',
        name: 'Vận tải Xuyên Việt',
        phone: '0901 234 567',
        email: 'ops@vantaiviet.vn',
        type: 'TRANSPORT',
        serviceSummary: 'Xe tham quan',
        operatingArea: 'Hà Nội, Quảng Ninh, Ninh Bình',
        address: '31 Trần Quang Khải, Hà Nội',
        establishedYear: 2014,
        description: 'Nhà xe chuyên tour ghép và tour riêng.',
        isActive: true,
      },
      {
        id: 'SUP003',
        name: 'SkyLink Airways Services',
        phone: '028 3822 5566',
        email: 'groupdesk@skylink.example',
        type: 'TRANSPORT',
        serviceSummary: 'Vé máy bay đoàn',
        operatingArea: 'Hà Nội, Hồ Chí Minh, Đà Nẵng, Quảng Ninh',
        address: '21 Láng Hạ, Ba Đình, Hà Nội',
        establishedYear: 2017,
        description: 'Đại lý vé máy bay đoàn cho tour nội địa và outbound.',
        isActive: true,
      },
      {
        id: 'SUP004',
        name: 'The Lotus Dining Room',
        phone: '024 3888 7777',
        email: 'reserve@lotus.vn',
        type: 'RESTAURANT',
        serviceSummary: 'Bữa ăn đoàn',
        operatingArea: 'Hà Nội',
        address: '88 Tràng Tiền, Hoàn Kiếm, Hà Nội',
        establishedYear: 2011,
        description: 'Nhà hàng chuyên set menu cho khách du lịch đoàn.',
        isActive: false,
      },
      {
        id: 'SUP005',
        name: 'Hạ Long Harbor Dining',
        phone: '0203 3888 889',
        email: 'booking@halongharbor.example',
        type: 'RESTAURANT',
        serviceSummary: 'Bữa ăn đoàn',
        operatingArea: 'Quảng Ninh',
        address: '28 Bãi Cháy, Hạ Long, Quảng Ninh',
        establishedYear: 2015,
        description: 'Nhà hàng phục vụ set menu đoàn tại Hạ Long.',
        isActive: true,
      },
    ],
  });

  await prisma.supplierServiceVariant.createMany({
    data: [
      {
        id: 'SUP001-S1',
        supplierId: 'SUP001',
        name: 'Phòng đôi',
        description: 'Phòng tiêu chuẩn hướng phố',
        unit: 'Phòng',
        quantity: 1,
        basePrice: 1300000,
      },
      {
        id: 'SUP001-S2',
        supplierId: 'SUP001',
        name: 'Phòng đơn',
        description: 'Phòng tiêu chuẩn giường lớn',
        unit: 'Phòng',
        quantity: 1,
        basePrice: 1200000,
      },
      {
        id: 'SUP001-S3',
        supplierId: 'SUP001',
        name: 'Ph\u00f2ng ba',
        description: 'Ph\u00f2ng ti\u00eau chu\u1ea9n cho 3 kh\u00e1ch',
        unit: 'Ph\u00f2ng',
        quantity: 1,
        basePrice: 1500000,
      },
      {
        id: 'SUP001-M1',
        supplierId: 'SUP001',
        name: 'Buffet sáng',
        unit: 'Bữa',
        quantity: 1,
        basePrice: 180000,
        isMealService: true,
        menu: 'Buffet 20 món + nước ép',
        note: 'Phục vụ từ 06:00-09:30',
      },
      {
        id: 'SUP002-S1',
        supplierId: 'SUP002',
        name: 'Xe 16 chỗ',
        description: 'Đồng hành suốt hành trình',
        unit: 'Xe',
        quantity: 1,
        capacity: 16,
        basePrice: 8100000,
        transportType: 'XE',
        priceMode: 'QUOTED',
      },
      {
        id: 'SUP002-S2',
        supplierId: 'SUP002',
        name: 'Xe 25 chỗ',
        description: 'Phương án dự phòng',
        unit: 'Xe',
        quantity: 1,
        capacity: 25,
        basePrice: 9600000,
        transportType: 'XE',
        priceMode: 'QUOTED',
      },
      {
        id: 'SUP003-S1',
        supplierId: 'SUP003',
        name: 'Vé máy bay đoàn nội địa',
        description: 'Áp dụng hành trình có chặng bay đoàn.',
        unit: 'Vé',
        quantity: 1,
        transportType: 'MAYBAY',
        priceMode: 'LISTED',
        basePrice: 1850000,
      },
      {
        id: 'SUP004-S1',
        supplierId: 'SUP004',
        name: 'Set menu đoàn',
        description: 'Phục vụ bàn tròn 10 người',
        unit: 'Người',
        quantity: 1,
        basePrice: 180000,
        menu: '6 món + canh + tráng miệng',
        note: 'Có menu chay theo yêu cầu',
      },
      {
        id: 'SUP005-S1',
        supplierId: 'SUP005',
        name: 'Set hải sản đoàn',
        description: 'Thực đơn đoàn 10 khách tại Hạ Long.',
        unit: 'Người',
        quantity: 1,
        basePrice: 198000,
        isMealService: true,
        menu: '8 món hải sản + canh + tráng miệng',
        note: 'Có lựa chọn thực đơn trẻ em',
      },
    ],
  });

  await prisma.supplierServicePrice.createMany({
    data: [
      { serviceVariantId: 'SUP001-S1', unitPrice: 1300000, fromDate: toDate('2026-01-01'), toDate: toDate('2026-12-31'), note: 'Giá chuẩn', createdByName: 'Điều phối viên' },
      { serviceVariantId: 'SUP001-S2', unitPrice: 1200000, fromDate: toDate('2026-01-01'), toDate: toDate('2026-12-31'), note: 'Giá chuẩn', createdByName: 'Điều phối viên' },
      { serviceVariantId: 'SUP001-M1', unitPrice: 180000, fromDate: toDate('2026-01-01'), toDate: toDate('2026-12-31'), note: 'Áp dụng nội khu', createdByName: 'Điều phối viên' },
      { serviceVariantId: 'SUP001-S3', unitPrice: 1500000, fromDate: toDate('2026-01-01'), toDate: toDate('2026-12-31'), note: 'Giá chuẩn', createdByName: 'Điều phối viên' },
      { serviceVariantId: 'SUP002-S1', unitPrice: 8100000, fromDate: toDate('2026-04-01'), toDate: toDate('2026-09-30'), note: 'Xe 16 chỗ', createdByName: 'Điều phối viên' },
      { serviceVariantId: 'SUP002-S2', unitPrice: 9600000, fromDate: toDate('2026-04-01'), toDate: toDate('2026-09-30'), note: 'Xe 25 chỗ', createdByName: 'Điều phối viên' },
      { serviceVariantId: 'SUP003-S1', unitPrice: 1850000, fromDate: toDate('2026-01-01'), toDate: toDate('2026-12-31'), note: 'Giá chặng đoàn', createdByName: 'Điều phối viên' },
      { serviceVariantId: 'SUP004-S1', unitPrice: 180000, fromDate: toDate('2026-01-01'), toDate: toDate('2026-12-31'), note: 'Set menu cơ bản', createdByName: 'Điều phối viên' },
      { serviceVariantId: 'SUP005-S1', unitPrice: 198000, fromDate: toDate('2026-01-01'), toDate: toDate('2026-12-31'), note: 'Set hải sản cơ bản', createdByName: 'Điều phối viên' },
    ],
  });

  await prisma.service.createMany({
    data: [
      {
        id: 'service-1',
        code: 'SV-TKT',
        name: 'Vé tham quan Sun World',
        category: 'ATTRACTION_TICKET',
        unit: 'vé',
        priceMode: 'LISTED',
        priceSetup: 'BY_AGE',
        status: 'ACTIVE',
        description: 'Áp dụng cho các chương trình tham quan tại Quảng Ninh.',
        supplierName: 'Sun World Hạ Long',
        contactInfo: '024 3936 6666',
        province: 'Quảng Ninh',
      },
      {
        id: 'service-2',
        code: 'SV-INS',
        name: 'Bảo hiểm du lịch',
        category: 'OTHER',
        unit: 'khách',
        priceMode: 'LISTED',
        priceSetup: 'COMMON',
        status: 'ACTIVE',
        description: 'Áp dụng trực tiếp vào chi phí khác.',
        supplierName: 'Bảo Việt Travel Care',
        contactInfo: 'hotro@baoviet.example',
        formulaCount: 'DEFAULT_VALUE',
        formulaCountDefault: '1',
        formulaQuantity: 'DEFAULT_VALUE',
        formulaQuantityDefault: 'Theo số người',
      },
      {
        id: 'service-3',
        code: 'SV-TEAM',
        name: 'Đạo cụ team building',
        category: 'OTHER',
        unit: 'gói',
        priceMode: 'QUOTED',
        priceSetup: 'COMMON',
        status: 'ACTIVE',
        description: 'Chi phí khác cần báo giá theo từng tour.',
        supplierName: 'Event House',
        contactInfo: 'event@travela.example',
        formulaCount: 'MANUAL',
        formulaQuantity: 'DEFAULT_VALUE',
        formulaQuantityDefault: '1',
      },
    ],
  });

  await prisma.servicePrice.createMany({
    data: [
      { serviceId: 'service-1', unitPrice: 250000, effectiveDate: toDate('2026-01-01'), endDate: toDate('2026-06-30'), note: 'Người lớn', createdByName: 'Trưởng phòng điều phối' },
      { serviceId: 'service-1', unitPrice: 180000, effectiveDate: toDate('2026-01-01'), endDate: toDate('2026-06-30'), note: 'Trẻ em', createdByName: 'Trưởng phòng điều phối' },
      { serviceId: 'service-2', unitPrice: 40000, effectiveDate: toDate('2026-01-01'), endDate: toDate('2026-12-31'), note: 'Bảo hiểm nội địa', createdByName: 'Điều phối viên' },
    ],
  });

  await prisma.tourGuide.createMany({
    data: [
      {
        code: 'HDV001',
        fullName: 'Trần Minh Hoàng',
        gender: 'MALE',
        dateOfBirth: toDate('1986-04-12'),
        phone: '0901 111 222',
        email: 'hoang.hdv@travela.vn',
        address: '25 Nguyễn Chí Thanh, Hà Nội',
        operatingArea: 'Miền Bắc',
        guideCardNumber: 'HDV-001-2020',
        issueDate: toDate('2020-03-20'),
        expiryDate: toDate('2030-03-20'),
        issuePlace: 'Tổng cục Du lịch',
        note: 'Phụ trách tour nội địa miền Bắc',
        languagesJson: ['Tiếng Anh'],
      },
      {
        code: 'HDV002',
        fullName: 'Lê Thu Hà',
        gender: 'FEMALE',
        dateOfBirth: toDate('1992-08-21'),
        phone: '0902 333 444',
        email: 'ha.hdv@travela.vn',
        address: '15 Lý Thường Kiệt, Hà Nội',
        operatingArea: 'Nhật Bản',
        guideCardNumber: 'HDV-002-2021',
        issueDate: toDate('2021-05-11'),
        expiryDate: toDate('2031-05-11'),
        issuePlace: 'Sở Du lịch Hà Nội',
        note: 'Ưu tiên tour inbound Nhật Bản',
        languagesJson: ['Tiếng Nhật', 'Tiếng Anh'],
      },
    ],
  });

  await prisma.voucher.createMany({
    data: [
      {
        code: 'SUMMER2026',
        type: 'PERCENT',
        valueAmount: 20,
        startsAt: toDate('2026-06-01'),
        endsAt: toDate('2026-08-31'),
        usageLimit: 200,
        usedCount: 0,
        status: 'DRAFT',
        description: 'Khuyến mãi mùa hè 2026',
        createdById: sales.id,
      },
      {
        code: 'PROMO10PCT',
        type: 'PERCENT',
        valueAmount: 10,
        startsAt: toDate('2026-04-20'),
        endsAt: toDate('2026-12-31'),
        usageLimit: 100,
        usedCount: 15,
        status: 'PENDING_APPROVAL',
        description: 'Giảm 10% cho tour chọn lọc',
        createdById: sales.id,
      },
      {
        code: 'VIP50PCT',
        type: 'PERCENT',
        valueAmount: 50,
        startsAt: toDate('2026-04-01'),
        endsAt: toDate('2026-06-30'),
        usageLimit: 10,
        usedCount: 0,
        status: 'REJECTED',
        description: 'Voucher bị từ chối do giá trị quá cao',
        rejectionReason: 'Giá trị giảm quá cao, vui lòng giảm xuống 30%',
        createdById: sales.id,
      },
      {
        code: 'LUXURY500K',
        type: 'FIXED',
        valueAmount: 500000,
        startsAt: toDate('2026-01-01'),
        endsAt: toDate('2026-12-31'),
        usageLimit: 50,
        usedCount: 12,
        status: 'ACTIVE',
        description: 'Giảm 500K cho đơn hàng cao cấp',
        createdById: sales.id,
        approvedById: manager.id,
      },
    ],
  });

  await prisma.blogPost.createMany({
    data: [
      {
        slug: 'cam-nang-du-thuyen-ha-long',
        title: 'Cẩm Nang Du Thuyền Hạ Long',
        category: 'Cẩm nang',
        excerpt: 'Những điều cần chuẩn bị trước khi lên du thuyền Hạ Long.',
        contentMarkdown: '# Cẩm nang\n\nChuẩn bị giấy tờ, trang phục và thuốc cá nhân.',
        coverImageUrl: 'https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=1400',
        publishedAt: toDate('2026-03-10'),
      },
      {
        slug: 'kinh-nghiem-ngam-la-do-kyoto',
        title: 'Kinh Nghiệm Ngắm Lá Đỏ Kyoto',
        category: 'Kinh nghiệm',
        excerpt: 'Thời điểm đẹp nhất để ngắm lá đỏ tại Kyoto.',
        contentMarkdown: '# Kyoto mùa thu\n\nNên đặt sớm để giữ chỗ.',
        coverImageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1400',
        publishedAt: toDate('2026-03-15'),
      },
    ],
  });

  await prisma.booking.create({
    data: {
      id: 'B001',
      bookingCode: 'BK-582910',
      tourInstanceId: instances[0].id,
      userId: customer.id,
      status: 'CONFIRMED',
      refundStatus: 'NONE',
      paymentMethod: 'PAYOS',
      paymentType: 'ONLINE',
      paymentStatus: 'PAID',
      contactName: 'Nguyễn Văn A',
      contactEmail: 'nguyenvana@gmail.com',
      contactPhone: '0988 888 888',
      contactNote: 'Dị ứng hải sản nhẹ',
      roomCountsJson: { single: 1, double: 0, triple: 0 },
      totalAmount: 9000000,
      paidAmount: 9000000,
      remainingAmount: 0,
      confirmedById: sales.id,
      confirmedAt: toDate('2026-03-25T11:00:00Z'),
      passengers: {
        create: [
          { type: 'ADULT', fullName: 'Nguyễn Văn A', gender: 'MALE', dateOfBirth: toDate('1985-05-12'), cccd: '001085012345', nationality: 'Việt Nam' },
          { type: 'ADULT', fullName: 'Trần Thị B', gender: 'FEMALE', dateOfBirth: toDate('1987-08-20'), cccd: '001087067890', nationality: 'Việt Nam' },
        ],
      },
      paymentTransactions: {
        create: [
          { amount: 9000000, method: 'PAYOS', status: 'PAID', paidAt: toDate('2026-03-25T10:45:00Z'), transactionRef: 'PAYOS-17000001', orderCode: '17000001' },
        ],
      },
    },
  });

  await prisma.booking.create({
    data: {
      id: 'B002',
      bookingCode: 'BK-102938',
      tourInstanceId: instances[1].id,
      userId: customer.id,
      status: 'PENDING_CANCEL',
      refundStatus: 'PENDING',
      paymentMethod: 'PAYOS',
      paymentType: 'ONLINE',
      paymentStatus: 'PAID',
      contactName: 'Nguyễn Văn A',
      contactEmail: 'nguyenvana@gmail.com',
      contactPhone: '0988 888 888',
      bankInfoJson: { accountNumber: '1234567890', bankName: 'Vietcombank', accountHolder: 'NGUYEN VAN A' },
      totalAmount: 32000000,
      paidAmount: 32000000,
      remainingAmount: 0,
      cancellationReason: 'Thay đổi kế hoạch công tác',
      cancelledAt: toDate('2026-04-05T10:00:00Z'),
      refundAmount: 25600000,
      payloadJson: {
        cancelledConfirmedBy: 'Nhân Viên Kinh Doanh',
        cancelledConfirmedAt: '2026-04-05T10:30:00Z',
      },
      passengers: {
        create: [
          { type: 'ADULT', fullName: 'Nguyễn Văn A', gender: 'MALE', dateOfBirth: toDate('1985-05-12'), cccd: '001085012345', nationality: 'Việt Nam' },
        ],
      },
      paymentTransactions: {
        create: [
          { amount: 32000000, method: 'PAYOS', status: 'PAID', paidAt: toDate('2026-03-26T08:20:00Z'), transactionRef: 'PAYOS-17000002', orderCode: '17000002' },
        ],
      },
    },
  });

  await prisma.booking.create({
    data: {
      id: 'B003',
      bookingCode: 'BK-394821',
      tourInstanceId: instances[4].id,
      userId: customer.id,
      status: 'PENDING',
      refundStatus: 'NONE',
      paymentMethod: 'PAYOS',
      paymentType: 'ONLINE',
      paymentStatus: 'PARTIAL',
      contactName: 'Lê Văn C',
      contactEmail: 'levanc@gmail.com',
      contactPhone: '0912 345 678',
      roomCountsJson: { single: 1, double: 1, triple: 0 },
      totalAmount: 56000000,
      paidAmount: 28000000,
      remainingAmount: 28000000,
      passengers: {
        create: [
          { type: 'ADULT', fullName: 'Lê Văn C', gender: 'MALE', dateOfBirth: toDate('1990-03-15'), cccd: '001090034567', nationality: 'Việt Nam', singleRoomSupplement: 500000 },
          { type: 'ADULT', fullName: 'Phạm Thị D', gender: 'FEMALE', dateOfBirth: toDate('1992-07-22'), cccd: '001092078901', nationality: 'Việt Nam' },
          { type: 'CHILD', fullName: 'Lê Minh E', gender: 'MALE', dateOfBirth: toDate('2018-01-10') },
        ],
      },
      paymentTransactions: {
        create: [
          { amount: 28000000, method: 'PAYOS', status: 'PAID', paidAt: toDate('2026-03-24T14:10:00Z'), transactionRef: 'PAYOS-17000003', orderCode: '17000003' },
        ],
      },
    },
  });

  await prisma.booking.create({
    data: {
      id: 'B004',
      bookingCode: 'BK-847291',
      tourInstanceId: instances[3].id,
      userId: customer.id,
      status: 'COMPLETED',
      refundStatus: 'NONE',
      paymentMethod: 'PAYOS',
      paymentType: 'ONLINE',
      paymentStatus: 'PAID',
      contactName: 'Hoang Van F',
      contactEmail: 'hoangvanf@gmail.com',
      contactPhone: '0977 654 321',
      totalAmount: 9000000,
      paidAmount: 9000000,
      remainingAmount: 0,
      passengers: {
        create: [
          { type: 'ADULT', fullName: 'Hoang Van F', gender: 'MALE', dateOfBirth: toDate('1988-11-05'), cccd: '001088056789', nationality: 'Viet Nam' },
          { type: 'ADULT', fullName: 'Vu Thi G', gender: 'FEMALE', dateOfBirth: toDate('1990-09-18'), cccd: '001090098765', nationality: 'Viet Nam' },
        ],
      },
      paymentTransactions: {
        create: [
          { amount: 4500000, method: 'PAYOS', status: 'PAID', paidAt: toDate('2026-03-20T09:50:00Z'), transactionRef: 'PAYOS-17000004', orderCode: '17000004' },
          { amount: 4500000, method: 'PAYOS', status: 'PAID', paidAt: toDate('2026-04-09T10:00:00Z'), transactionRef: 'PAYOS-17000005', orderCode: '17000005' },
        ],
      },
    },
  });

  await resetBookingFixtures(prisma);
  await resetCustomerPublicFixtures(prisma);
  await resetTourWorkflowFixtures(prisma);
  await resetVoucherFixtures(prisma);

  console.log('Seed completed.');
  console.log('Accounts:');
  console.log('admin@travela.vn / 123456');
  console.log('manager@travela.vn / 123456');
  console.log('coordinator@travela.vn / 123456');
  console.log('sales@travela.vn / 123456');
  console.log('customer@travela.vn / 123456');
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
